# Generated by Django 4.2 on 2023-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='svgfile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='svgfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='svgfile',
            name='type',
        ),
        migrations.AddField(
            model_name='svgfile',
            name='file',
            field=models.FileField(null=True, upload_to='static/main/'),
        ),
    ]
