# Generated by Django 4.2 on 2023-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_svgfile_link_remove_svgfile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgfile',
            name='file',
            field=models.FileField(null=True, upload_to='%Y-%m-%d:%H:%M:%S'),
        ),
    ]
